name: Common CI - Reusable Workflow

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2

    - name: Node.js Setup
      uses: actions/setup-node@v2
    - name: Installation of Node.js dependencies
      run: npm install
    - name: Running Tests
      run: npm run pretest && npm run test
    - name: Running Coverage
      run: npm run coverage
